import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className='flex flex-col items-center'>
      <Image className="mx-auto" src={'/raah.jpeg'} height={250} width={250} alt={'logo'}></Image>
      <Head>
        <title>Raah Donation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className="text-5xl font-bold mt-5">Welcome to RAAH</h1>

        <h2 className='mt-20 text-2xl'>
          <Link href={"/login"}>&rarr; Login</Link>
        </h2>
        <h2 className='mt-8 text-2xl'>
          <Link href={"/signup"}>&rarr; SignUp </Link>
        </h2>
      
    </div>
  );
}
